// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// solvecpp
arma::mat solvecpp(const arma::mat& A);
RcppExport SEXP _MFSGrp_solvecpp(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(solvecpp(A));
    return rcpp_result_gen;
END_RCPP
}
// maxeigencpp
double maxeigencpp(const arma::mat& X);
RcppExport SEXP _MFSGrp_maxeigencpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(maxeigencpp(X));
    return rcpp_result_gen;
END_RCPP
}
// normcpp
double normcpp(const arma::vec& x, const arma::mat& A, bool euc);
RcppExport SEXP _MFSGrp_normcpp(SEXP xSEXP, SEXP ASEXP, SEXP eucSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< bool >::type euc(eucSEXP);
    rcpp_result_gen = Rcpp::wrap(normcpp(x, A, euc));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MFSGrp_solvecpp", (DL_FUNC) &_MFSGrp_solvecpp, 1},
    {"_MFSGrp_maxeigencpp", (DL_FUNC) &_MFSGrp_maxeigencpp, 1},
    {"_MFSGrp_normcpp", (DL_FUNC) &_MFSGrp_normcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_MFSGrp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
