# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solvecpp <- function(A) {
    .Call('_MFSGrp_solvecpp', PACKAGE = 'MFSGrp', A)
}

maxeigencpp <- function(X) {
    .Call('_MFSGrp_maxeigencpp', PACKAGE = 'MFSGrp', X)
}

normcpp <- function(x, A, euc = TRUE) {
    .Call('_MFSGrp_normcpp', PACKAGE = 'MFSGrp', x, A, euc)
}

